import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import Providers from '@/lib/Providers'
import SessionProvider from './components/SessionProvider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <Providers>
      <html lang="en">
        <SessionProvider session={session}>
          <body>
            <AntdRegistry>{children}</AntdRegistry>
          </body>
        </SessionProvider>
      </html>
    </Providers>
  )
}
